# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 03:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170807_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7535\u8bdd')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u7bb1')),
                ('message', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237',
                'verbose_name_plural': '\u5ba2\u6237',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('type_video', '\u89c6\u9891'), ('type_phtoto', '\u6444\u5f71'), ('type_travel', '\u6e38\u8bb0'), ('type_program', '\u7f16\u7a0b')], max_length=20, verbose_name='\u7c7b\u578b')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=polls.models.pic_upload_path, verbose_name='\u5c01\u9762')),
                ('article_description', models.TextField(blank=True, null=True, verbose_name='\u6982\u89c8')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u6b63\u6587')),
                ('video', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u89c6\u9891\u94fe\u63a5')),
                ('date', models.DateField(verbose_name='\u53d1\u5e03\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u8bb0\u5f55',
                'verbose_name_plural': '\u65f6\u95f4\u8f74',
            },
        ),
        migrations.CreateModel(
            name='RecordImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_img', models.ImageField(blank=True, null=True, upload_to=polls.models.pic_upload_path, verbose_name='\u6444\u5f71\u56fe\u7247')),
                ('remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs_set', to='polls.Record')),
            ],
            options={
                'verbose_name_plural': '\u56fe\u7247',
            },
        ),
    ]
