# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_contactdata_record_recordimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
