#!/bin/bash

mv ./mysite_nginx.conf /etc/nginx/default.d/
nginx

./mysite/manage.py migrate
./mysite/manage.py collectstatic --noinput

nohup uwsgi --ini mysite_uwsgi.ini > /root/logs/docker_app.log &







