# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', '\u7537'), ('f', '\u5973')], max_length=10),
        ),
    ]
